services:

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://workflow_user:workflow_pass@postgres:5432/workflow_db
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: workflow_user
      POSTGRES_PASSWORD: workflow_pass
      POSTGRES_DB: workflow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: